package com.rbac.model;
// Generated Jan 30, 2017 10:05:45 AM by Hibernate Tools 4.3.1.Final

/**
 * AcessType generated by hbm2java
 */
public class AcessType implements java.io.Serializable {

	private Integer id;
	private String name;

	public AcessType() {
	}

	public AcessType(String name) {
		this.name = name;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

}
