package com.rbac.model;
// Generated Jan 31, 2017 9:22:44 AM by Hibernate Tools 4.3.1.Final

/**
 * AcessType generated by hbm2java
 */
public class Keys implements java.io.Serializable {

	private Integer id;
	private String masterSecretKey;
	private String publicKey;

	public Keys() {
	}

	public Keys(String masterSecretKey, String publicKey) {
		this.masterSecretKey = masterSecretKey;
		this.publicKey = publicKey;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public String getMasterSecretKey() {
		return this.masterSecretKey;
	}

	public void setMasterSecretKey(String masterSecretKey) {
		this.masterSecretKey = masterSecretKey;
	}
	
	@Override
	public String toString() {
		return id + ") " + masterSecretKey;
	}

	public String getPublicKey() {
		return publicKey;
	}

	public void setPublicKey(String publicKey) {
		this.publicKey = publicKey;
	}
	
}
