package com.rbac.model;
// Generated Jan 30, 2017 10:05:45 AM by Hibernate Tools 4.3.1.Final

import java.util.HashSet;
import java.util.Set;

/**
 * Permission generated by hbm2java
 */
public class Permission implements java.io.Serializable {

	private Integer id;
	private Integer accesstypeid;
	private Integer resourceid;
	private Boolean status;
	private Set<RolePermission> rolePermissions = new HashSet<RolePermission>(0);

	public Permission() {
	}

	public Permission(Integer accesstypeid, Integer resourceid, Boolean status, Set<RolePermission> rolePermissions) {
		this.accesstypeid = accesstypeid;
		this.resourceid = resourceid;
		this.status = status;
		this.rolePermissions = rolePermissions;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public Integer getAccesstypeid() {
		return this.accesstypeid;
	}

	public void setAccesstypeid(Integer accesstypeid) {
		this.accesstypeid = accesstypeid;
	}

	public Integer getResourceid() {
		return this.resourceid;
	}

	public void setResourceid(Integer resourceid) {
		this.resourceid = resourceid;
	}

	public Boolean getStatus() {
		return this.status;
	}

	public void setStatus(Boolean status) {
		this.status = status;
	}

	public Set<RolePermission> getRolePermissions() {
		return this.rolePermissions;
	}

	public void setRolePermissions(Set<RolePermission> rolePermissions) {
		this.rolePermissions = rolePermissions;
	}

}
