package com.rbac.model;
// Generated Jan 30, 2017 10:05:45 AM by Hibernate Tools 4.3.1.Final

/**
 * Resource generated by hbm2java
 */
public class Resource implements java.io.Serializable {

	private Integer id;
	private String name;
	private String path;
	private Boolean status;

	public Resource() {
	}

	public Resource(String name, String path, Boolean status) {
		this.name = name;
		this.path = path;
		this.status = status;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public String getPath() {
		return this.path;
	}

	public void setPath(String path) {
		this.path = path;
	}

	public Boolean getStatus() {
		return this.status;
	}

	public void setStatus(Boolean status) {
		this.status = status;
	}

}
