package com.rbac.model;
// Generated Jan 31, 2017 9:22:44 AM by Hibernate Tools 4.3.1.Final

/**
 * RolePermission generated by hbm2java
 */
public class RolePermission implements java.io.Serializable {

	private Integer id;
	private Permission permission;
	private Role role;
	private Boolean status;

	public RolePermission() {
	}

	public RolePermission(Permission permission, Role role, Boolean status) {
		this.permission = permission;
		this.role = role;
		this.status = status;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public Permission getPermission() {
		return this.permission;
	}

	public void setPermission(Permission permission) {
		this.permission = permission;
	}

	public Role getRole() {
		return this.role;
	}

	public void setRole(Role role) {
		this.role = role;
	}

	public Boolean getStatus() {
		return this.status;
	}

	public void setStatus(Boolean status) {
		this.status = status;
	}

}
